# Generated by Django 2.1.2 on 2018-10-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utube_groupies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='viewers',
        ),
        migrations.AddField(
            model_name='theater',
            name='crashers',
            field=models.ManyToManyField(related_name='parties', to='utube_groupies.User'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='invitees',
            field=models.ManyToManyField(related_name='events', to='utube_groupies.User'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='utube_groupies.User'),
        ),
    ]
