# Generated by Django 2.1.2 on 2018-10-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utube_groupies', '0002_auto_20181024_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='attendees',
            field=models.ManyToManyField(related_name='events', to='utube_groupies.User'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='invitees',
            field=models.ManyToManyField(related_name='invitations', to='utube_groupies.User'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seshes', to='utube_groupies.User'),
        ),
    ]
