# Generated by Django 2.1.2 on 2018-10-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utube_groupies', '0003_auto_20181024_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='status',
            field=models.CharField(default='stop', max_length=45),
            preserve_default=False,
        ),
    ]
